import os
import re
import base64
from pathlib import Path

import argparse
import numpy as np
import pandas as pd
import netCDF4 as nc

from loguru import logger
from alchemlyb.workflows import ABFE
from alchemlyb.postprocessors.units import kJ2kcal, R_kJmol


#Boltzmann Constant in kcal/mol
B = kJ2kcal * R_kJmol

class NCFilePostProcessing:

    """
    Post-processing utilities for YANK/OpenMM NetCDF output files.

    This class provides tools to extract thermodynamic information from
    NetCDF files generated by YANK simulations, including:

    - Standard state corrections
    - Lambda schedules
    - Reduced potential energies (u_nk)

    The extracted data are converted into formats compatible with
    `alchemlyb` for free energy analysis.
    """

    def __init__(
        self,
        nc_file : Path,
        T : float = 298.15,
        skiplambda : int = None
    ):
        """
        Initialize the NetCDF post-processing object.

        Parameters
        ----------
        nc_file : Path
            Path to the NetCDF file generated by YANK.
        T : float, optional
            Temperature of the simulation in Kelvin.
        skiplambda : int, optional
            Lambda state to be skipped during the analysis.
        """
        
        # Define the simulation phase (e.g., complex or solvent)
        self.phase = nc_file.stem

        logger.info(f"Starting alchemical analysis for {self.phase.upper()} phase")
        
        # Open the NetCDF dataset
        self.dataset = nc.Dataset(nc_file)

        # Store temperature and skipped lambda index
        self.__T = T
        self.__skiplambda = skiplambda

    def extract_standard_correction(self) -> tuple[float, float]:
        
        """
        Extract the standard state correction stored in the NetCDF metadata.

        Returns
        -------
        tuple
            A tuple containing:
            - Standard state correction in kT
            - Standard state correction in kcal/mol
        """

        logger.info("Extracting standard state correction...")

        # Retrieve the stored correction from metadata
        raw_standard_correction = self.dataset.groups['metadata'].variables.get(
            'standard_state_correction', None
        )

        if raw_standard_correction is not None:

            # Decode binary data stored as text
            standard_correction_binary = b''.join(raw_standard_correction).decode()

            # Extract the base64 encoded string
            b64 = re.search(r'!!binary \|\n\s+(.+)', standard_correction_binary).group(1)

            # Decode the base64 data
            binary_data = base64.b64decode(b64)

            # Convert binary buffer into float64
            standard_correction_kT: float = -np.frombuffer(binary_data, dtype=np.float64)[0]

            # Convert to kcal/mol
            standard_correction_kcal_mol: float = standard_correction_kT * B * self.__T

            return standard_correction_kT, standard_correction_kcal_mol

    @staticmethod
    def extract_lambdas(thermodynamic_states: nc.Group) -> pd.DataFrame:
        """
        Extract lambda values from the thermodynamic states stored in the NetCDF file.

        Parameters
        ----------
        thermodynamic_states : nc.Group
            NetCDF group containing the thermodynamic state definitions.

        Returns
        -------
        pandas.DataFrame
            DataFrame containing lambda values for each alchemical state.
        """

        logger.info("Extracting thermodynamic lambda states...")

        # Define the expected lambda ordering
        order = ['lambda_restraints', 'lambda_electrostatics', 'lambda_sterics']

        rows = []

        for name, var in thermodynamic_states.variables.items():

            # Extract binary representation of the lambda definition
            raw = var[:]
            text = b''.join(raw).decode()

            # Parse lambda values using regex
            lambdas = dict(re.findall(r'(lambda_\w+):\s*([0-9\.eE+-]+)', text))

            # Keep the predefined order
            lambdas = {k: float(lambdas[k]) for k in order if k in lambdas}

            rows.append(lambdas)

        logger.info(f"{len(rows)} lambda states extracted")

        df = pd.DataFrame(rows)

        # Convert electrostatic and steric lambdas to the alchemlyb convention
        df.loc[:, ['lambda_electrostatics', 'lambda_sterics']] = (
            1.0 - df.loc[:, ['lambda_electrostatics', 'lambda_sterics']]
        )

        return df

    @staticmethod
    def extract_u_nk(
        array: np.ndarray,
        current_lambda: pd.Series,
        labels: list,
        columns: list,
        time: pd.Series,
        temperature: float = 298.15,
        energy_unit: str = "kT",
    ) -> pd.DataFrame:
        """
        Convert raw reduced potentials into an alchemlyb-compatible u_nk DataFrame.

        Parameters
        ----------
        array : np.ndarray
            Matrix containing reduced potentials with shape (n_samples, n_states).
        current_lambda : pd.Series
            Lambda values corresponding to the current thermodynamic state.
        labels : list
            Lambda labels.
        columns : list
            Column index describing the lambda states.
        time : pd.Series
            Simulation time index.
        temperature : float, optional
            Simulation temperature in Kelvin.
        energy_unit : str, optional
            Unit of the reduced potential energies.

        Returns
        -------
        pandas.DataFrame
            u_nk DataFrame compatible with alchemlyb estimators.
        """

        logger.debug(f"Extracting energies for lambda state {current_lambda}. Shape: {array.shape}")

        if time.name != "time":
            raise ValueError(f"The name of the time index ({time.name}) must be 'time'.")

        n_samples, n_lambdas = array.shape

        if n_samples != len(time):
            raise ValueError(
                f"The length of the time array ({len(time)}) does not match "
                f"the number of samples ({n_samples})."
            )

        # Build the u_nk dataframe
        u_nk = pd.DataFrame(
            data=array,
            index=time,
            columns=columns,
        )

        # Ensure numeric type
        u_nk = u_nk.apply(pd.to_numeric, errors="coerce")

        # Add lambda values as index levels
        for i, key in enumerate(labels):
            u_nk[key] = current_lambda[i]

        # Create multi-index
        newind = ["time"] + list(labels)
        u_nk = u_nk.reset_index().set_index(newind)

        u_nk.name = "u_nk"
        u_nk.attrs = {"temperature": temperature, "energy_unit": energy_unit}

        return u_nk

    def extract_yank_to_unk(self) -> list:
        """
        Extract energy data from a YANK NetCDF file and convert it into
        the ``u_nk`` format used by alchemlyb.

        This method reconstructs the reduced potential matrix for each
        thermodynamic state by identifying which replica occupied that
        state at every iteration. Energies are then expressed relative
        to the sampled state and optionally filtered to remove a specific
        lambda state.

        Returns
        -------
        list of pandas.DataFrame
            A list of ``u_nk`` DataFrames, one for each lambda state. Each
            DataFrame contains the reduced potentials evaluated at all
            thermodynamic states and is indexed by time and lambda values.

        Notes
        -----
        - Energies stored in the YANK NetCDF file are assumed to be in units
        of ``kT``.
        - Replica exchange trajectories are reconstructed using the
        ``states`` variable, which stores the state index visited by each
        replica at every iteration.
        - If ``skiplambda`` is defined, the corresponding state is removed
        from the energy matrix after the relative energy transformation.
        """

        logger.info("Extracting energies from netCDF4 file...")

        # Extract raw energy and state information
        energies = self.dataset['energies'][:].data  # shape: (n_iterations, n_replica, n_states)
        states = self.dataset['states'][:].data      # shape: (n_iterations, n_replica)
        n_iterations, n_replica, n_states = energies.shape

        # Extract lambda values corresponding to each thermodynamic state
        lambdas = self.extract_lambdas(self.dataset.groups['thermodynamic_states'])

        # List that will contain the resulting u_nk DataFrames
        u_nk_list = []

        lambda_dict = lambdas.to_dict()
        labels = list(lambda_dict.keys())

        # Remove the skipped lambda from the column definition if required
        lambdas_filtered = lambdas.drop(index=self.__skiplambda) if self.__skiplambda is not None else lambdas
        columns = [tuple(row) for _, row in lambdas_filtered.iterrows()]

        for state_idx in range(n_states):

            # Skip the selected lambda state if requested
            if state_idx != self.__skiplambda:

                # For each iteration, identify which replica was visiting this state
                replicas_in_state = np.array([
                    np.where(states[it] == state_idx)[0][0]
                    for it in range(n_iterations)
                ])

                # Remove iterations where the skipped lambda replica appears
                valid_iterations = np.where(replicas_in_state != self.__skiplambda)[0]
                replicas_clean = replicas_in_state[valid_iterations]

                # Extract energies of the corresponding replica evaluated at all states
                # Resulting shape: (n_valid_iterations, n_states)
                u_k = energies[valid_iterations, replicas_clean, :]

                # Convert energies to relative values by subtracting the sampled state's energy
                u_k -= u_k[:, state_idx].reshape(-1, 1)

                # Remove the skipped lambda column after the energy shift
                if self.__skiplambda is not None:
                    u_k = np.delete(u_k, self.__skiplambda, axis=1)

                # Build the time index
                time = pd.Series(data=valid_iterations, name='time', dtype="Float64")

                # Lambda values corresponding to the current state
                current_lambda = tuple(lambdas.iloc[state_idx])

                # Convert to alchemlyb u_nk format
                u_nk = self.extract_u_nk(
                    array=u_k,
                    current_lambda=current_lambda,
                    labels=labels,
                    columns=columns,
                    time=time,
                    temperature=self.__T,
                    energy_unit='kT'  # YANK stores energies in kT
                )

                u_nk_list.append(u_nk)

        logger.info("Energy extraction completed!")

        return u_nk_list

    def close(self):

        if self.dataset.isopen():
            self.dataset.close()


class ABFE_YANK(ABFE,NCFilePostProcessing):
    
    """Workflow for absolute and relative binding free energy calculations.

    This workflow provides functionality similar to the ``alchemical-analysis.py`` script.
    It loads multiple input files from alchemical free energy calculations and computes the
    free energies between different alchemical windows using different estimators. It
    produces plots to aid in the assessment of convergence.

    Parameters
    ----------
    T : float
        Temperature in K.
    units : str
        The unit used for printing and plotting results. {'kcal/mol', 'kJ/mol',
        'kT'}. Default: 'kT'.
    software : str
        The software used for generating input (case-insensitive). {'GROMACS', 'AMBER', 'PARQUET'}.
        This option chooses the appropriate parser for the input file.
    dir : str
        Directory in which data files are stored. Default: os.path.curdir.
    prefix : str
        Prefix for datafile sets. This argument accepts regular expressions and
        the input files are searched using
        ``Path(dir).glob("**/" + prefix + "*" + suffix)``. Default: 'dhdl'.
    suffix : str
        Suffix for datafile sets. Default: 'xvg'.
    outdirectory : str
        Directory in which the output files produced by this script will be
        stored. Default: os.path.curdir.

    Attributes
    ----------
    logger : Logger
        The logging object.
    file_list : list
        The list of filenames sorted by the lambda state.


    .. versionadded:: 1.0.0
    .. versionchanged:: 2.0.1
        The `dir` argument expects a real directory without wildcards and wildcards will no longer
        work as expected. Use `prefix` to specify wildcard-based patterns to search under `dir`.
    .. versionchanged:: 2.1.0
        The serialised dataframe could be read via software='PARQUET'.
    """

    def __init__(
        self,
        T: float,
        units: str = "kT",
        software: str = "OPENMM",
        dir: str = os.curdir,
        prefix: str = "dhdl",
        suffix: str = "xvg",
        outdirectory: str = os.curdir,
        skiplambda: int = None
    ) -> None:
        
        # Trick parent constructor
        super().__init__(
            T=T,
            units=units,
            software="GROMACS",
            dir=dir,
            prefix=prefix,
            suffix=suffix,
            outdirectory=outdirectory
        )

        NCFilePostProcessing.__init__(
            self,
            nc_file=Path(dir).joinpath(f"{prefix}.{suffix}"),
            T=T,
            skiplambda=skiplambda
        )

        self.software = software
        
        if self.software == "OPENMM":
            self._extract_u_nk = self.extract_yank_to_unk
            self._extract_dHdl = None
        
    def read(
        self, read_u_nk: bool = True, read_dHdl: bool = True, n_jobs: int = 1
    ) -> None:
        """Read the u_nk and dHdL data from the
        :attr:`~alchemlyb.workflows.ABFE.file_list`

        Parameters
        ----------
        read_u_nk : bool
            Whether to read the u_nk.
        read_dHdl : bool
            Whether to read the dHdl.
        n_jobs : int
            Number of parallel workers to use for reading the data.
            (-1 means using all the threads)

        Attributes
        ----------
        u_nk_list : list
            A list of :class:`pandas.DataFrame` of u_nk.
        dHdl_list : list
            A list of :class:`pandas.DataFrame` of dHdl.
        """
        self.u_nk_sample_list = None  # type: ignore[assignment]
        self.dHdl_sample_list = None  # type: ignore[assignment]

        if self.software == 'OPENMM':
            u_nk_list = self._extract_u_nk()
            self.u_nk_list = u_nk_list
            self.dHdl_list = []
        else:
            super().read(read_u_nk=read_u_nk, read_dHdl=read_dHdl, n_jobs=n_jobs)




if __name__ == "__main__":

    parser = argparse.ArgumentParser()

    parser.add_argument('-f', '--input', type=str, required=True, help='netCDF4 file.')
    parser.add_argument('-n', '--njobs', type=int, required=True, help='njobs.')
    parser.add_argument('-T', '--temperature', type=float, required=True, help='Temperature.')
    parser.add_argument('-s', '--skiplambda', type=str, nargs='*', required=False, default=[None, None], help='Lambda to skip.')
    parser.add_argument('-o', '--output', type=str, required=True, help='Output.')

    args = parser.parse_args()

    def parse_skiplambda(value):
        if value is None or value == 'None':
            return None
        return int(value)

    skiplambdas = [parse_skiplambda(v) for v in args.skiplambda]

    config = {
        'skiptime':0.0,
        'uncorr':'dE',
        'threshold':50,
        'estimators':('MBAR', 'BAR'),
        'overlap':'O_MBAR.pdf',
        'breakdown':True,
        'forwrev':10,
        'n_jobs': args.njobs
    }

    phases = ['complex', 'solvent']

    results = {}
    for i, phase in enumerate(phases):

        try:
    
            workflow = ABFE_YANK(
                units='kcal/mol', 
                dir=args.input, 
                T=float(args.temperature), 
                outdirectory=f"{args.output}/{phase}",
                prefix=phase,
                suffix='nc',
                software='OPENMM',
                skiplambda=skiplambdas[i]
            )
            
        
            workflow.run(**config)

            summary = workflow.summary

            value = summary.loc[('Stages', 'TOTAL'), 'MBAR']
            error = summary.loc[('Stages', 'TOTAL'), 'MBAR_Error']

            results[phase]=(value,error)

            if phase == 'complex':
                standard_correction_kT, standard_correction_kcak_mol = workflow.extract_standard_correction()
            
            workflow.close()
        
        except Exception as e:
            workflow.close()
            raise Exception(f"Failure due to {e}")
    
    
    if len(results)>1:
        
        dG = standard_correction_kcak_mol+results['solvent'][0]-results['complex'][0]
        dG_error = np.sqrt(results['solvent'][1]**2+results['complex'][1]**2)
        concentration = np.exp(dG/(B*args.temperature)) / 1.0e-6
        
        print(f"Results:\n \
            Complex leg: {results['complex'][0]:.3f} +- {results['complex'][1]:.3f} kcal/mol\n \
            Solvent leg: {results['solvent'][0]:.3f} +- {results['solvent'][1]:.3f} kcal/mol\n \
            Standard correction: {standard_correction_kT:.3f} kT; {standard_correction_kcak_mol:.3f} kcal/mol\n \
            Final result: {dG:.2f} +- {dG_error:.2f} kcal/mol | {concentration:.2f} µM"
        )